const { app, BrowserWindow, globalShortcut, ipcMain, Menu, nativeImage, powerMonitor, screen, session, shell, Tray } = require('electron')
const { spawn } = require('node:child_process')
const { lstatSync, readdirSync, readFileSync, realpathSync, statSync, writeFileSync } = require('node:fs')
const os = require('node:os')
const path = require('node:path')
const { parsePowerShellJson } = require('./desktop-json.cjs')
const { minimizeDisposition } = require('./window-mode.cjs')

const JARVIS_URL = process.env.JARVIS_UI_URL || 'http://127.0.0.1:7711'
const TRUSTED_ORIGINS = new Set(['http://127.0.0.1:7711', 'http://localhost:7711'])

const APP_COMMANDS = Object.freeze({
  calculator: ['calc.exe'],
  notepad: ['notepad.exe'],
  explorer: ['explorer.exe'],
  terminal: ['wt.exe'],
  task_manager: ['taskmgr.exe'],
  chrome: ['cmd.exe', '/c', 'start', '', 'chrome'],
  edge: ['cmd.exe', '/c', 'start', '', 'msedge'],
  browser: ['cmd.exe', '/c', 'start', '', 'msedge'],
  vscode: ['cmd.exe', '/c', 'start', '', 'code'],
  spotify: ['cmd.exe', '/c', 'start', '', 'spotify'],
})
const APP_PROCESS_NAMES = Object.freeze({
  calculator: ['CalculatorApp.exe', 'Calculator.exe'],
  notepad: ['Notepad.exe'],
  explorer: ['explorer.exe'],
  terminal: ['WindowsTerminal.exe', 'wt.exe'],
  task_manager: ['Taskmgr.exe'],
  chrome: ['chrome.exe'],
  edge: ['msedge.exe'],
  browser: ['msedge.exe'],
  vscode: ['Code.exe'],
  spotify: ['Spotify.exe'],
})

const FOLDERS = Object.freeze({
  jarvis: process.env.JARVIS_ROOT_DIR || path.resolve(__dirname, '..', '..', '..'),
  desktop: app.getPath('desktop'),
  downloads: app.getPath('downloads'),
  documents: app.getPath('documents'),
})

let mainWindow = null
let tray = null
let quitting = false
let gpuSnapshotCache = { capturedAt: 0, value: null }
let currentWindowMode = 'full'
let presentationPending = true
let collapseTimer = null
let dashboardAuthenticated = false
let lastWakePresentationAt = 0
const actionReceipts = []

const STARTUP_PRESENTATION_MS = 14_000
const OVERLAY_WIDTH = 460
const OVERLAY_HEIGHT = 680

function recordAction(operation, target, details = {}) {
  actionReceipts.push({ timestamp: new Date().toISOString(), operation, target: String(target).slice(0, 240), details })
  if (actionReceipts.length > 100) actionReceipts.splice(0, actionReceipts.length - 100)
}

const INPUT_ACTIONS = new Set(['cursor_move', 'cursor_click', 'click_element', 'type_text', 'key_press'])
const ALLOWED_KEYS = new Set(['ENTER', 'TAB', 'ESCAPE', 'BACKSPACE', 'DELETE', 'UP', 'DOWN', 'LEFT', 'RIGHT', 'HOME', 'END', 'PAGEUP', 'PAGEDOWN', 'CTRL+A', 'CTRL+C', 'CTRL+V', 'CTRL+F', 'CTRL+L', 'CTRL+S', 'ALT+TAB'])

// Spoken responses are generated by the trusted local TTS service after an
// asynchronous voice/text turn. Preserve that user-requested playback across
// the IPC + network round trip inside this local-only shell.
app.commandLine.appendSwitch('autoplay-policy', 'no-user-gesture-required')

function trustedUrl(value) {
  try {
    return TRUSTED_ORIGINS.has(new URL(value).origin)
  } catch {
    return false
  }
}

function trustedSender(event) {
  return trustedUrl(event.senderFrame.url)
}

function overlayStatePath() {
  return path.join(app.getPath('userData'), 'overlay-state.json')
}

function readOverlayBounds() {
  try {
    const parsed = JSON.parse(readFileSync(overlayStatePath(), 'utf8'))
    if ([parsed.x, parsed.y, parsed.width, parsed.height].every(Number.isFinite)) return parsed
  } catch { /* first launch or invalid local state */ }
  return null
}

function saveOverlayBounds() {
  if (!mainWindow || mainWindow.isDestroyed() || currentWindowMode !== 'overlay') return
  const bounds = mainWindow.getBounds()
  try { writeFileSync(overlayStatePath(), JSON.stringify(bounds), 'utf8') } catch { /* position persistence is best effort */ }
}

function appRoute(route) {
  return new URL(route, `${JARVIS_URL.replace(/\/$/, '')}/`).toString()
}

function clearCollapseTimer() {
  if (collapseTimer) clearTimeout(collapseTimer)
  collapseTimer = null
}

function defaultOverlayBounds() {
  const display = screen.getDisplayNearestPoint(screen.getCursorScreenPoint())
  const area = display.workArea
  const width = Math.min(OVERLAY_WIDTH, area.width - 32)
  const height = Math.min(OVERLAY_HEIGHT, area.height - 32)
  return { x: area.x + area.width - width - 18, y: area.y + area.height - height - 18, width, height }
}

function enterOverlay({ focus = false } = {}) {
  if (!mainWindow || mainWindow.isDestroyed()) return
  // Never squeeze authentication into the compact surface. The renderer marks
  // the dashboard ready only after the protected command deck has mounted.
  if (!dashboardAuthenticated) {
    enterFullDeck({ presentation: presentationPending })
    return
  }
  clearCollapseTimer()
  currentWindowMode = 'overlay'
  if (mainWindow.isFullScreen()) mainWindow.setFullScreen(false)
  if (mainWindow.isMaximized()) mainWindow.unmaximize()
  mainWindow.setAlwaysOnTop(true, 'floating')
  mainWindow.setSkipTaskbar(false)
  mainWindow.setMinimumSize(360, 480)
  const saved = readOverlayBounds()
  const target = saved || defaultOverlayBounds()
  const display = screen.getDisplayMatching(target)
  const area = display.workArea
  const width = Math.max(360, Math.min(target.width, area.width - 24))
  const height = Math.max(480, Math.min(target.height, area.height - 24))
  const x = Math.max(area.x + 12, Math.min(target.x, area.x + area.width - width - 12))
  const y = Math.max(area.y + 12, Math.min(target.y, area.y + area.height - height - 12))
  mainWindow.setBounds({ x, y, width, height })
  const reveal = () => focus ? (mainWindow.show(), mainWindow.focus()) : mainWindow.showInactive()
  if (!mainWindow.webContents.getURL().includes('/overlay')) {
    mainWindow.webContents.once('did-finish-load', reveal)
    void mainWindow.loadURL(appRoute('/overlay'))
  } else reveal()
}

function enterFullDeck({ presentation = false } = {}) {
  if (!mainWindow || mainWindow.isDestroyed()) return
  saveOverlayBounds()
  clearCollapseTimer()
  currentWindowMode = 'full'
  presentationPending = presentation
  mainWindow.setAlwaysOnTop(false)
  mainWindow.setMinimumSize(960, 680)
  const reveal = () => {
    mainWindow.maximize()
    mainWindow.show()
    mainWindow.focus()
  }
  if (!mainWindow.webContents.getURL().includes('/dashboard')) {
    mainWindow.webContents.once('did-finish-load', reveal)
    void mainWindow.loadURL(appRoute('/dashboard'))
  } else reveal()
}

function schedulePresentationCollapse() {
  if (!presentationPending || currentWindowMode !== 'full') return
  presentationPending = false
  clearCollapseTimer()
  collapseTimer = setTimeout(() => enterOverlay(), STARTUP_PRESENTATION_MS)
}

function presentAfterWake() {
  const now = Date.now()
  // Windows commonly emits resume and unlock-screen for the same wake cycle.
  if (now - lastWakePresentationAt < 3_000) return
  lastWakePresentationAt = now
  enterFullDeck({ presentation: true })
}

function runDetached(executable, args = []) {
  const child = spawn(executable, args, { detached: true, stdio: 'ignore', windowsHide: true })
  child.unref()
}

function processIsRunning(imageNames, timeoutMs = 2_500) {
  const expected = imageNames.map((value) => value.toLowerCase())
  return new Promise((resolve) => {
    const child = spawn('tasklist.exe', ['/FO', 'CSV', '/NH'], { stdio: ['ignore', 'pipe', 'ignore'], windowsHide: true })
    let output = ''
    let settled = false
    const finish = (value) => {
      if (settled) return
      settled = true
      clearTimeout(timer)
      resolve(value)
    }
    const timer = setTimeout(() => { child.kill(); finish(false) }, timeoutMs)
    child.stdout.setEncoding('utf8')
    child.stdout.on('data', (chunk) => { if (output.length < 1_000_000) output += chunk })
    child.once('error', () => finish(false))
    child.once('close', (code) => {
      const haystack = output.toLowerCase()
      finish(code === 0 && expected.some((name) => haystack.includes(`"${name}"`)))
    })
  })
}

function canonicalApprovedFile(filePath) {
  const resolved = realpathSync(path.resolve(filePath))
  const allowed = Object.values(FOLDERS).map((folder) => realpathSync(folder).toLowerCase())
  const normalized = resolved.toLowerCase()
  if (!allowed.some((root) => normalized === root || normalized.startsWith(`${root}${path.sep}`))) throw new Error('That file is outside the approved local folders.')
  if (!statSync(resolved).isFile()) throw new Error('The resolved target is not a file.')
  return resolved
}

function searchApprovedFiles({ scope = 'downloads', query = '', extension = '' } = {}) {
  if (!Object.hasOwn(FOLDERS, scope)) throw new Error('That search location is not approved.')
  const root = realpathSync(FOLDERS[scope])
  const needle = String(query).trim().toLowerCase()
  const suffix = String(extension).trim().toLowerCase().replace(/^\./, '')
  const results = []
  const pending = [{ directory: root, depth: 0 }]
  let inspected = 0
  while (pending.length && inspected < 4_000 && results.length < 20) {
    const current = pending.shift()
    let entries = []
    try { entries = readdirSync(current.directory, { withFileTypes: true }) } catch { continue }
    for (const entry of entries) {
      if (inspected++ >= 4_000) break
      const candidate = path.join(current.directory, entry.name)
      let metadata
      try {
        const link = lstatSync(candidate)
        if (link.isSymbolicLink()) continue
        metadata = statSync(candidate)
      } catch { continue }
      if (entry.isDirectory()) {
        if (current.depth < 3 && !entry.name.startsWith('.')) pending.push({ directory: candidate, depth: current.depth + 1 })
        continue
      }
      if (!entry.isFile()) continue
      const name = entry.name.toLowerCase()
      if (needle && !name.includes(needle)) continue
      if (suffix && path.extname(name).slice(1) !== suffix) continue
      results.push({ name: entry.name, path: candidate, modifiedAt: metadata.mtime.toISOString(), sizeBytes: metadata.size })
    }
  }
  return results.sort((left, right) => right.modifiedAt.localeCompare(left.modifiedAt)).slice(0, 10)
}

function cpuTimes() {
  return os.cpus().reduce((totals, cpu) => {
    totals.idle += cpu.times.idle
    totals.total += Object.values(cpu.times).reduce((sum, value) => sum + value, 0)
    return totals
  }, { idle: 0, total: 0 })
}

async function sampleCpuPercent() {
  const before = cpuTimes()
  await new Promise((resolve) => setTimeout(resolve, 180))
  const after = cpuTimes()
  const total = Math.max(1, after.total - before.total)
  return Math.max(0, Math.min(100, Math.round((1 - (after.idle - before.idle) / total) * 100)))
}

function sampleNvidiaGpu() {
  if (Date.now() - gpuSnapshotCache.capturedAt < 5_000) return Promise.resolve(gpuSnapshotCache.value)
  return new Promise((resolve) => {
    const child = spawn('nvidia-smi.exe', ['--query-gpu=name,utilization.gpu,memory.used,memory.total,temperature.gpu', '--format=csv,noheader,nounits'], { stdio: ['ignore', 'pipe', 'ignore'], windowsHide: true })
    let output = ''
    const timer = setTimeout(() => { child.kill(); resolve(null) }, 2_500)
    child.stdout.setEncoding('utf8')
    child.stdout.on('data', (chunk) => { if (output.length < 2_048) output += chunk })
    child.once('error', () => { clearTimeout(timer); resolve(null) })
    child.once('close', (code) => {
      clearTimeout(timer)
      if (code !== 0) { resolve(null); return }
      const [name, utilization, memoryUsed, memoryTotal, temperature] = output.trim().split(',').map((value) => value.trim())
      if (!name || !Number.isFinite(Number(memoryTotal))) { resolve(null); return }
      const value = { name, utilizationPercent: Number(utilization), memoryUsedMb: Number(memoryUsed), memoryTotalMb: Number(memoryTotal), temperatureC: Number(temperature) }
      gpuSnapshotCache = { capturedAt: Date.now(), value }
      resolve(value)
    })
  })
}

function desktopScriptPath(scriptName) {
  if (app.isPackaged) return path.join(process.resourcesPath, 'app.asar.unpacked', 'desktop', scriptName)
  return path.join(__dirname, scriptName)
}

function runDesktopScript(scriptName, args = [], timeoutMs = 8_000) {
  return new Promise((resolve, reject) => {
    const child = spawn('powershell.exe', [
      '-NoLogo', '-NoProfile', '-NonInteractive', '-ExecutionPolicy', 'Bypass',
      '-File', desktopScriptPath(scriptName), ...args,
    ], { stdio: ['ignore', 'pipe', 'pipe'], windowsHide: true })
    const stdoutChunks = []
    let stdoutBytes = 0
    let stderr = ''
    let settled = false
    const finish = (callback) => {
      if (settled) return
      settled = true
      clearTimeout(timer)
      callback()
    }
    const timer = setTimeout(() => {
      child.kill()
      finish(() => reject(new Error('The bounded desktop action timed out.')))
    }, timeoutMs)
    child.stderr.setEncoding('utf8')
    child.stdout.on('data', (chunk) => {
      stdoutChunks.push(Buffer.from(chunk))
      stdoutBytes += chunk.length
      if (stdoutBytes > 1_000_000) child.kill()
    })
    child.stderr.on('data', (chunk) => { stderr += chunk })
    child.on('error', (error) => finish(() => reject(error)))
    child.on('close', (code) => finish(() => {
      if (code !== 0) {
        reject(new Error((stderr || 'The desktop action failed.').trim().slice(0, 500)))
        return
      }
      try {
        resolve(parsePowerShellJson(stdoutChunks))
      } catch {
        reject(new Error('The desktop action returned an invalid local response.'))
      }
    }))
  })
}

function hideForUnderlyingApp() {
  const shouldRestore = Boolean(mainWindow && !mainWindow.isDestroyed() && mainWindow.isVisible())
  if (shouldRestore) mainWindow.hide()
  return async () => {
    if (!shouldRestore || !mainWindow || mainWindow.isDestroyed()) return
    await new Promise((resolve) => setTimeout(resolve, 80))
    mainWindow.showInactive()
  }
}

async function inspectDesktopContext() {
  const restore = hideForUnderlyingApp()
  try {
    await new Promise((resolve) => setTimeout(resolve, 180))
    return await runDesktopScript('windows-context.ps1', ['-MaxElements', '160'], 7_000)
  } finally {
    await restore()
  }
}

function integerCoordinate(value, label) {
  if (!Number.isInteger(value) || value < -20_000 || value > 20_000) throw new Error(`${label} must be a valid desktop coordinate.`)
  return String(value)
}

async function runInputAction(action) {
  const type = String(action.type ?? '')
  if (!INPUT_ACTIONS.has(type)) throw new Error('That input action is not allowlisted.')
  const values = action.arguments && typeof action.arguments === 'object' ? action.arguments : {}
  const args = ['-Action', type]
  if (type === 'cursor_move' || type === 'cursor_click') {
    args.push('-X', integerCoordinate(values.x, 'X'), '-Y', integerCoordinate(values.y, 'Y'))
  }
  if (type === 'cursor_click') {
    const button = values.button === 'right' ? 'right' : 'left'
    const clicks = values.clicks === 2 ? 2 : 1
    args.push('-Button', button, '-Clicks', String(clicks))
  }
  if (type === 'click_element') {
    const query = String(values.query ?? action.target ?? '').trim()
    if (!query || query.length > 120) throw new Error('An accessible element name between 1 and 120 characters is required.')
    args.push('-Query', query)
  }
  if (type === 'type_text') {
    const text = String(values.text ?? '')
    if (!text || text.length > 500 || /[\u0000-\u0008\u000B\u000C\u000E-\u001F]/.test(text)) throw new Error('Typed text must contain 1-500 safe characters.')
    args.push('-Text', text)
  }
  if (type === 'key_press') {
    const key = String(values.key ?? action.target ?? '').trim().toUpperCase()
    if (!ALLOWED_KEYS.has(key)) throw new Error('That key is outside the local key allowlist.')
    args.push('-Key', key)
  }
  const restore = hideForUnderlyingApp()
  try {
    await new Promise((resolve) => setTimeout(resolve, 180))
    return await runDesktopScript('windows-input.ps1', args, 8_000)
  } finally {
    await restore()
  }
}

function createWindow() {
  mainWindow = new BrowserWindow({
    width: 1560,
    height: 980,
    minWidth: 960,
    minHeight: 680,
    show: false,
    frame: false,
    backgroundColor: '#02070d',
    title: 'J.A.R.V.I.S. Neural Operating Interface',
    autoHideMenuBar: true,
    webPreferences: {
      preload: path.join(__dirname, 'preload.cjs'),
      contextIsolation: true,
      nodeIntegration: false,
      sandbox: true,
      webSecurity: true,
    },
  })

  mainWindow.once('ready-to-show', () => {
    mainWindow.show()
    mainWindow.maximize()
  })

  mainWindow.on('close', (event) => {
    if (quitting) return
    event.preventDefault()
    mainWindow.hide()
  })
  mainWindow.on('minimize', (event) => {
    if (minimizeDisposition({ authenticated: dashboardAuthenticated, currentMode: currentWindowMode }) !== 'overlay') return
    event.preventDefault()
    enterOverlay()
  })
  mainWindow.on('move', saveOverlayBounds)
  mainWindow.on('resize', saveOverlayBounds)

  mainWindow.webContents.setWindowOpenHandler(({ url }) => {
    if (url.startsWith('https://')) void shell.openExternal(url)
    return { action: 'deny' }
  })
  mainWindow.webContents.on('will-navigate', (event, url) => {
    try {
      if (!TRUSTED_ORIGINS.has(new URL(url).origin)) event.preventDefault()
    } catch {
      event.preventDefault()
    }
  })

  void mainWindow.loadURL(JARVIS_URL)
}

function showMainWindow() {
  if (!mainWindow || mainWindow.isDestroyed()) createWindow()
  enterFullDeck()
}

function createTray() {
  if (tray) return
  const iconPath = path.join(__dirname, 'jarvis-icon.png')
  const icon = nativeImage.createFromPath(iconPath).resize({ width: 20, height: 20 })
  tray = new Tray(icon)
  tray.setToolTip('J.A.R.V.I.S. Neural Interface')
  tray.setContextMenu(Menu.buildFromTemplate([
    { label: 'Open full command deck', click: showMainWindow },
    { label: 'Show compact overlay', click: () => enterOverlay({ focus: true }) },
    { label: 'Hide interface', click: () => mainWindow?.hide() },
    { type: 'separator' },
    { label: 'Quit desktop interface', click: () => { quitting = true; app.quit() } },
  ]))
  tray.on('click', showMainWindow)
}

app.setAppUserModelId('dev.jarvis.maheer.desktop')
if (!app.requestSingleInstanceLock()) app.quit()

app.on('second-instance', () => {
  showMainWindow()
})

app.whenReady().then(() => {
  // Electron performs a permission check before (and, depending on Chromium
  // version, sometimes without) issuing the permission request callback. Both
  // gates must allow the trusted local dashboard or getUserMedia fails with a
  // generic NotAllowedError even though Windows microphone privacy is enabled.
  session.defaultSession.setPermissionCheckHandler((webContents, permission, requestingOrigin) => {
    const origin = requestingOrigin || webContents?.getURL() || ''
    return permission === 'media' && trustedUrl(origin)
  })
  session.defaultSession.setPermissionRequestHandler((webContents, permission, callback, details) => {
    const origin = details?.requestingUrl || webContents.getURL()
    callback(permission === 'media' && trustedUrl(origin))
  })

  ipcMain.handle('jarvis:system-snapshot', async (event) => {
    if (!trustedSender(event)) throw new Error('Untrusted renderer')
    const [cpuUsagePercent, gpu] = await Promise.all([sampleCpuPercent(), sampleNvidiaGpu()])
    return {
      hostname: os.hostname(),
      platform: `${os.type()} ${os.release()}`,
      uptimeSeconds: Math.floor(os.uptime()),
      totalMemoryGb: Math.round(os.totalmem() / 1024 ** 2) / 1024,
      freeMemoryGb: Math.round(os.freemem() / 1024 ** 2) / 1024,
      cpuCount: os.cpus().length,
      cpuUsagePercent,
      gpu,
      desktop: true,
    }
  })

  ipcMain.handle('jarvis:screen-context', async (event) => {
    if (!trustedSender(event)) throw new Error('Untrusted renderer')
    return inspectDesktopContext()
  })

  ipcMain.handle('jarvis:desktop-action', async (event, action) => {
    if (!trustedSender(event)) throw new Error('Untrusted renderer')
    if (!action || typeof action.type !== 'string') {
      throw new Error('Invalid desktop action')
    }

    if (INPUT_ACTIONS.has(action.type)) {
      const result = await runInputAction(action)
      const delivered = result.success === true
      if (delivered) recordAction(`input_${action.type}`, String(result.evidence?.matched ?? action.target ?? action.type), { deliveryVerified: true })
      return {
        success: delivered,
        message: delivered ? `${result.message} Windows verified delivery of the input event.` : (result.message || 'Windows rejected the input event.'),
        evidence: { ...(result.evidence || {}), verified: delivered, verification: 'windows_input_delivery' },
      }
    }

    if (action.type === 'process_snapshot') {
      const result = await runDesktopScript('windows-control.ps1', ['-Action', 'process_snapshot'], 8_000)
      const processes = Array.isArray(result.processes) ? result.processes : []
      const summary = processes.slice(0, 5).map((item, index) => `${index + 1}. ${item.name} (${item.memoryMb} MB)`).join('; ')
      return { success: result.success === true, message: summary ? `Highest current memory consumers: ${summary}.` : 'No process snapshot was available.', evidence: { verified: result.verified === true, count: processes.length } }
    }

    if (action.type === 'action_history') {
      const recent = actionReceipts.slice(-10).reverse()
      const summary = recent.map((item) => `${item.operation.replaceAll('_', ' ')}: ${item.target}`).join('; ')
      return { success: true, message: summary ? `In this session I verified these actions: ${summary}.` : 'I have not made any verified PC changes in this session.', evidence: { verified: true, count: recent.length } }
    }

    if (action.type === 'file_search') {
      const values = action.arguments && typeof action.arguments === 'object' ? action.arguments : {}
      const matches = searchApprovedFiles(values)
      const first = matches[0]
      return {
        success: true,
        message: first ? `Found ${matches.length} matching file${matches.length === 1 ? '' : 's'}. Newest: ${first.name}.` : 'No matching files were found in the approved folder.',
        evidence: { verified: true, count: matches.length, ...(first ? { path: first.path, name: first.name, modifiedAt: first.modifiedAt } : {}) },
      }
    }

    if (action.type === 'open_file') {
      const values = action.arguments && typeof action.arguments === 'object' ? action.arguments : {}
      const resolved = canonicalApprovedFile(String(values.path ?? action.target ?? ''))
      const error = await shell.openPath(resolved)
      if (error) throw new Error(error)
      recordAction('open_file', resolved)
      return { success: true, message: `Opened ${path.basename(resolved)}.`, evidence: { verified: true, path: resolved } }
    }

    if (action.type === 'window_control') {
      const values = action.arguments && typeof action.arguments === 'object' ? action.arguments : {}
      const query = String(values.query ?? action.target ?? '').trim()
      const operation = String(values.operation ?? '')
      const allowedOperations = new Set(['focus', 'minimize', 'maximize', 'restore', 'snap_left', 'snap_right', 'move_monitor'])
      if (!query || query.length > 120 || !allowedOperations.has(operation)) throw new Error('A valid named window operation is required.')
      const args = ['-Action', 'window_control', '-Query', query, '-Operation', operation]
      if (operation === 'move_monitor') {
        const monitor = Number(values.monitor)
        if (!Number.isInteger(monitor) || monitor < 1 || monitor > 16) throw new Error('A valid monitor number is required.')
        args.push('-Monitor', String(monitor))
      }
      const result = await runDesktopScript('windows-control.ps1', args, 10_000)
      if (result.success === true && result.verified === true) recordAction(`window_${operation}`, String(result.target ?? query), { processId: Number(result.processId ?? 0) })
      return {
        success: result.success === true && result.verified === true,
        message: result.success === true && result.verified === true ? `${operation.replaceAll('_', ' ')} completed for ${result.target} and verified.` : `The ${operation.replaceAll('_', ' ')} operation could not be verified.`,
        evidence: { process: String(result.target ?? ''), processId: Number(result.processId ?? 0), verified: result.verified === true, monitorCount: Number(result.monitorCount ?? 0) },
      }
    }

    if (action.type === 'open_app' && typeof action.target === 'string' && Object.hasOwn(APP_COMMANDS, action.target)) {
      const focusTarget = action.target === 'browser' ? 'browser' : action.target
      try {
        const focused = await runDesktopScript('windows-control.ps1', ['-Action', 'window_control', '-Query', focusTarget, '-Operation', 'focus'], 4_000)
        if (focused.success === true && focused.verified === true) {
          recordAction('focus_application', action.target)
          return { success: true, message: `Focused the existing ${action.target.replaceAll('_', ' ')} window and verified it.`, evidence: { process: String(focused.target ?? ''), verified: true } }
        }
      } catch { /* no existing visible window; launch one below */ }
      const [executable, ...args] = APP_COMMANDS[action.target]
      runDetached(executable, args)
      await new Promise((resolve) => setTimeout(resolve, 650))
      const processNames = APP_PROCESS_NAMES[action.target] || [path.basename(executable)]
      const verified = await processIsRunning(processNames)
      if (verified) recordAction('open_application', action.target)
      return verified
        ? { success: true, message: `Opened ${action.target.replaceAll('_', ' ')} and verified its process.`, evidence: { process: processNames[0], verified: true } }
        : { success: false, message: `Windows accepted the ${action.target.replaceAll('_', ' ')} launch request, but JARVIS could not verify the process.`, evidence: { process: processNames[0], verified: false } }
    }
    if (action.type === 'open_folder' && typeof action.target === 'string' && Object.hasOwn(FOLDERS, action.target)) {
      const error = await shell.openPath(FOLDERS[action.target])
      if (error) throw new Error(error)
      await new Promise((resolve) => setTimeout(resolve, 650))
      let verified = false
      let processName = ''
      try {
        const result = await runDesktopScript('windows-control.ps1', ['-Action', 'window_control', '-Query', action.target, '-Operation', 'focus'], 5_000)
        verified = result.success === true && result.verified === true
        processName = String(result.target ?? '')
      } catch { /* Explorer accepted the path, but no matching window was observable. */ }
      if (verified) recordAction('open_folder', FOLDERS[action.target])
      return verified
        ? { success: true, message: `Opened the ${action.target} folder and verified its Explorer window.`, evidence: { verified: true, path: FOLDERS[action.target], process: processName } }
        : { success: true, message: `Windows accepted the ${action.target} folder request, but JARVIS could not verify the Explorer window.`, evidence: { verified: false, accepted: true, path: FOLDERS[action.target] } }
    }
    if (action.type === 'open_settings' && action.target === 'windows') {
      await shell.openExternal('ms-settings:')
      await new Promise((resolve) => setTimeout(resolve, 650))
      let verified = false
      try {
        const result = await runDesktopScript('windows-control.ps1', ['-Action', 'window_control', '-Query', 'Settings', '-Operation', 'focus'], 5_000)
        verified = result.success === true && result.verified === true
      } catch { /* Windows accepted the URI, but no Settings window was observable. */ }
      if (verified) recordAction('open_settings', 'windows')
      return verified
        ? { success: true, message: 'Opened Windows Settings and verified its window.', evidence: { verified: true } }
        : { success: true, message: 'Windows accepted the Settings request, but JARVIS could not verify its window.', evidence: { verified: false, accepted: true } }
    }
    if (action.type === 'system_action' && typeof action.target === 'string') {
      if (action.target === 'lock') runDetached('rundll32.exe', ['user32.dll,LockWorkStation'])
      else if (action.target === 'volume_mute') runDetached('powershell.exe', ['-NoProfile', '-WindowStyle', 'Hidden', '-Command', '(New-Object -ComObject WScript.Shell).SendKeys([char]173)'])
      else if (action.target === 'volume_up') runDetached('powershell.exe', ['-NoProfile', '-WindowStyle', 'Hidden', '-Command', '(New-Object -ComObject WScript.Shell).SendKeys([char]175)'])
      else if (action.target === 'volume_down') runDetached('powershell.exe', ['-NoProfile', '-WindowStyle', 'Hidden', '-Command', '(New-Object -ComObject WScript.Shell).SendKeys([char]174)'])
      else if (action.target === 'sleep') runDetached('rundll32.exe', ['powrprof.dll,SetSuspendState', '0,1,0'])
      else if (action.target === 'shutdown_pc') runDetached('shutdown.exe', ['/s', '/t', '5', '/c', 'JARVIS operator-approved shutdown'])
      else if (action.target === 'restart_pc') runDetached('shutdown.exe', ['/r', '/t', '5', '/c', 'JARVIS operator-approved restart'])
      else throw new Error('That system action is not in the local safety allowlist.')
      return {
        success: true,
        message: `Windows accepted the ${action.target.replaceAll('_', ' ')} request; completion cannot be verified before the system state changes.`,
        evidence: { verified: false, accepted: true, request: action.target },
      }
    }
    throw new Error('That desktop action is not in the local safety allowlist.')
  })

  ipcMain.handle('jarvis:window', (event, action) => {
    if (!trustedSender(event) || !mainWindow) return false
    if (action === 'minimize') {
      if (minimizeDisposition({ authenticated: dashboardAuthenticated, currentMode: currentWindowMode }) === 'overlay') enterOverlay()
      else mainWindow.minimize()
    }
    else if (action === 'toggle-maximize') mainWindow.isMaximized() ? mainWindow.unmaximize() : mainWindow.maximize()
    else if (action === 'close') mainWindow.hide()
    else return false
    return true
  })

  ipcMain.handle('jarvis:window-mode', (event, mode) => {
    if (!trustedSender(event)) return false
    if (mode === 'full') enterFullDeck()
    else if (mode === 'overlay') enterOverlay({ focus: true })
    else if (mode === 'hide') mainWindow?.hide()
    else return false
    return true
  })

  ipcMain.handle('jarvis:dashboard-ready', (event) => {
    if (!trustedSender(event)) return false
    dashboardAuthenticated = true
    schedulePresentationCollapse()
    return true
  })

  createWindow()
  createTray()
  globalShortcut.register('CommandOrControl+Space', () => {
    if (!mainWindow) return
    if (!mainWindow.isVisible()) enterOverlay({ focus: true })
    else if (currentWindowMode === 'overlay') enterFullDeck()
    else enterOverlay({ focus: true })
  })

  powerMonitor.on('resume', presentAfterWake)
  powerMonitor.on('unlock-screen', presentAfterWake)
})

app.on('window-all-closed', () => {})
app.on('before-quit', () => { quitting = true; clearCollapseTimer(); saveOverlayBounds() })
app.on('will-quit', () => globalShortcut.unregisterAll())
